/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './shared/**/*.{js,css}',
  ],
  // Classes built dynamically in JS template strings / classList (missed by scanner)
  safelist: [
    'hidden',
    'opacity-50',
    'opacity-60',
    'ring-2',
    'ring-emerald-400',
    'ring-amber-400',
    'cursor-not-allowed',
    'hover:underline',
    'min-w-0',
    'min-w-[150px]',
    'min-w-[170px]',
    'min-w-[520px]',
    'text-[11px]',
    'text-sm',
    'text-2xl',
    'text-white',
    'text-zinc-100',
    'text-zinc-200',
    'text-zinc-300',
    'text-zinc-400',
    'text-zinc-500',
    'text-zinc-600',
    'text-red-300',
    'text-red-400',
    'text-emerald-200',
    'text-emerald-300',
    'text-emerald-400',
    'text-emerald-400/90',
    'text-emerald-500/80',
    'text-amber-200/90',
    'text-amber-300',
    'text-amber-400',
    'text-amber-500/90',
    'text-violet-200',
    'text-violet-300',
    'text-[#a855f7]',
    'text-[#FDD700]',
    'text-[#e9d5ff]',
    'text-[#EAB308]',
    'text-black',
    'bg-[#FDD700]',
    'bg-amber-950',
    'bg-sky-950',
    'bg-green-950',
    'bg-emerald-950',
    'text-sky-300',
    'text-green-300',
    'border-amber-800',
    'border-emerald-800',
    'border-sky-800',
    'border-green-800',
    'border-red-800',
    'border-zinc-500',
    'hover:border-zinc-500',
    'transition-colors',
    'bg-zinc-800',
    'bg-zinc-900',
    'bg-zinc-950',
    'bg-red-950',
    'bg-violet-950',
    'bg-violet-950/50',
    'bg-emerald-950',
    'border',
    'border-zinc-600',
    'border-zinc-700',
    'border-zinc-800',
    'border-emerald-700',
    'border-emerald-700/70',
    'border-red-700',
    'border-violet-500',
    'border-violet-600',
    'border-amber-700/30',
    'hover:bg-zinc-800',
    'hover:bg-zinc-900',
    'hover:bg-red-900',
    'hover:bg-violet-900',
    'hover:text-white',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    'px-2',
    'px-3',
    'py-0.5',
    'py-1',
    'py-1.5',
    'py-2',
    'py-2.5',
    'mb-1',
    'mb-2',
    'mb-2.5',
    'mb-3',
    'mb-4',
    'mb-5',
    'mt-0.5',
    'mt-1',
    'mt-2',
    'mt-4',
    'space-y-2',
    'space-y-3',
    'space-y-6',
    'font-bold',
    'font-semibold',
    'font-medium',
    'uppercase',
    'tracking-wide',
    'whitespace-nowrap',
    'break-word',
    'tabular-nums',
    'shrink-0',
    'inline-block',
    'inline-flex',
    'items-center',
    'justify-between',
    'justify-center',
    'w-full',
    'flex',
    'flex-col',
    'gap-2',
    'gap-3',
    'p-3',
    'p-4',
    'sm:p-4',
    'sm:text-lg',
    'text-base',
    'text-lg',
    'text-center',
    'text-right',
    'leading-snug',
    // status badge colors (admin statusBadge)
    {
      pattern: /^(bg|text|border)-(emerald|amber|red|zinc|violet|sky|blue|green|yellow)-(100|200|300|400|500|600|700|800|900|950)$/,
      variants: ['hover'],
    },
  ],
  theme: {
    extend: {
      colors: {
        spbc: {
          forest: '#0B120E',
          gold: '#FDD700',
          gold2: '#EAB308',
        },
      },
      fontFamily: {
        inter: ['Inter', 'system-ui', 'sans-serif'],
        ducks: ['"Bebas Neue"', 'Impact', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
